'use strict';
const { fs, path, root, sha256, canonical, options, outputDirectory, exportsOf, validateOfficial, files } = require('./wuwa-build-common');
const wuwa = require('../src/core/wuwa-install');
function stage(args) {
  for (const required of ['official-resources', 'native', 'native-provenance', 'overlay', 'revision']) if (!args[required]) throw Error('Missing --' + required + '. See BUILD.md.');
  if (!/^[a-zA-Z0-9._-]{1,100}$/.test(args.revision)) throw Error('Revision must be a short release identifier.');
  const official = path.resolve(args['official-resources']), native = path.resolve(args.native), overlay = path.resolve(args.overlay);
  validateOfficial(official);
  const metadata = JSON.parse(fs.readFileSync(path.resolve(args['native-provenance']), 'utf8'));
  const nativeHash = sha256(native), overlayHash = sha256(overlay);
  if (metadata.controlAbi !== 1 || metadata.stateBytes !== 376 || metadata.commandBytes !== 24 || metadata.experimentEnabled !== true ||
      String(metadata.nativeSha256).toLowerCase() !== nativeHash || !path.isAbsolute(metadata.targetExe || '') || !/^[a-f0-9]{64}$/i.test(metadata.sourceSha256 || '')) throw Error('Require the ON native-build.json generated by the public native builder; binary/ABI/source record mismatch.');
  const suffix = path.win32.normalize(wuwa.TARGET_RELATIVE).toLowerCase();
  if (!canonical(metadata.targetExe).endsWith('\\' + suffix)) throw Error('Native target is not the full canonical Wuthering Waves Client executable.');
  const selectedRoot = metadata.targetExe.slice(0, metadata.targetExe.length - wuwa.TARGET_RELATIVE.length - 1);
  if (!wuwa.isTarget(metadata.targetExe, selectedRoot)) throw Error('Native target root/canonical path is invalid.');
  for (const [file, required] of [[native, ['RenoDX_WuWa_GetState', 'RenoDX_WuWa_SetControl']], [overlay, ['NAME', 'AddonInit', 'AddonUninit']]]) {
    const exported = exportsOf(file); for (const name of required) if (!exported.includes(name)) throw Error('Required export missing: ' + name);
  }
  for (const [flag, actual] of [['expected-native-sha256', nativeHash], ['expected-overlay-sha256', overlayHash]]) if (args[flag] && args[flag].toLowerCase() !== actual) throw Error('Explicit release pin mismatch: --' + flag);
  const output = outputDirectory(args.out || path.join(root, 'build-local/staged-resources'), [official, native, overlay, path.resolve(args['native-provenance'])], metadata.targetExe);
  if (fs.existsSync(output) && files(output).length) throw Error('Staging output must be a new/empty directory; old payloads are not silently reused.');
  fs.mkdirSync(output, { recursive: true });
  for (const directory of ['payload', 'overlay']) fs.cpSync(path.join(official, directory), path.join(output, directory), { recursive: true });
  const local = path.join(output, 'payload/wuwa'); fs.mkdirSync(local, { recursive: true });
  const previous = args['previous-manifest'] ? JSON.parse(fs.readFileSync(path.resolve(args['previous-manifest']), 'utf8')) : null;
  const previousHashes = key => Array.from(new Set([previous?.[key]?.sha256, ...(previous?.[key === 'native' ? 'previousNativeSha256' : 'previousOverlaySha256'] || [])].filter(value => /^[a-f0-9]{64}$/.test(value || '')))).slice(0, 32);
  const spec = { schema: 1, revision: args.revision, controlAbi: 1, targetExe: metadata.targetExe,
    native: { name: 'renodx-dlss5.addon64', sha256: nativeHash }, overlay: { name: 'dlss5-lab-overlay.addon64', sha256: overlayHash },
    previousNativeSha256: previousHashes('native'), previousOverlaySha256: previousHashes('overlay'),
    defaults: { NeuralUplift: '1', NRFollowInputRes: '0', NRResolutionScale: '0.85', WuWaCostMode: '1', NRPasses: '1', NRPreUpscale: '0', NRGpuTimers: '1' } };
  for (const [source, name] of [[native, spec.native.name], [overlay, spec.overlay.name]]) fs.copyFileSync(source, path.join(local, name));
  fs.writeFileSync(path.join(local, 'manifest.json'), JSON.stringify(spec, null, 2) + '\n');
  const plan = wuwa.plan(output, metadata.targetExe, selectedRoot);
  if (plan.native.hash !== nativeHash || plan.overlay.hash !== overlayHash) throw Error('Staged installer plan mismatch.');
  fs.writeFileSync(path.join(output, 'stage.local.json'), JSON.stringify({ revision: spec.revision, targetExe: spec.targetExe, nativeHash, overlayHash, nativeBuildSourceSha256: metadata.sourceSha256, originalPayloadImportedLocally: true, actualGameExecutionVerified: false }, null, 2) + '\n');
  return output;
}
if (require.main === module) { try { console.log(stage(options())); } catch (error) { console.error(error.message); process.exitCode = 1; } }
module.exports = { stage };
