#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <array>
#include <vector>
#include <fstream>
#include <string>
#include <iostream>
#include <stdexcept>
#include <cstring>
#include <iomanip>
#include <cmath>
#include <limits>
#include <algorithm>
using Microsoft::WRL::ComPtr;
static void check(HRESULT hr, const char* action) { if (FAILED(hr)) { char b[100]; sprintf_s(b,"%s: HRESULT 0x%08lx",action,(unsigned long)hr); throw std::runtime_error(b); } }
static std::vector<unsigned char> read(const std::string& path) { std::ifstream f(path,std::ios::binary); if(!f)throw std::runtime_error("Cannot read "+path); return {std::istreambuf_iterator<char>(f),{}}; }
static void write(const std::string& path,const void* data,size_t n) { std::ofstream f(path,std::ios::binary); f.write((const char*)data,n); if(!f)throw std::runtime_error("Cannot write "+path); }
struct Constants { uint32_t width,height,mw,mh,dw,dh,mx,my,dx,dy,encoding; float maxmotion,mvx,mvy,depthabs,depthrel,luma,colorrel,colorabs,residual; };
static_assert(sizeof(Constants)==80);
struct Input { uint32_t magic,mode; Constants c; std::array<float,256> current,edited; std::array<float,128> motion; std::array<float,64> depth; std::array<unsigned char,1280> history; };
static_assert(sizeof(Input)==4184);
static D3D12_HEAP_PROPERTIES heap(D3D12_HEAP_TYPE type) { D3D12_HEAP_PROPERTIES h{};h.Type=type;h.CreationNodeMask=h.VisibleNodeMask=1;return h; }
static D3D12_RESOURCE_DESC buffer(UINT64 bytes,D3D12_RESOURCE_FLAGS flags=D3D12_RESOURCE_FLAG_NONE) { D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=bytes;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=flags;return d; }
static ComPtr<ID3D12Resource> resource(ID3D12Device* device,const D3D12_RESOURCE_DESC& desc,D3D12_HEAP_TYPE ht,D3D12_RESOURCE_STATES state) { auto h=heap(ht);ComPtr<ID3D12Resource> r;check(device->CreateCommittedResource(&h,D3D12_HEAP_FLAG_NONE,&desc,state,nullptr,IID_PPV_ARGS(&r)),"CreateCommittedResource");return r; }
static void transition(ID3D12GraphicsCommandList* cmd,ID3D12Resource* r,D3D12_RESOURCE_STATES before,D3D12_RESOURCE_STATES after) { D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=r;b.Transition.StateBefore=before;b.Transition.StateAfter=after;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;cmd->ResourceBarrier(1,&b); }
static void uploadbuffer(ID3D12Device* dev,ID3D12GraphicsCommandList* cmd,ID3D12Resource* target,const void* data,size_t bytes,std::vector<ComPtr<ID3D12Resource>>& keep) { auto up=resource(dev,buffer(bytes),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);void* p=nullptr;D3D12_RANGE empty{0,0};check(up->Map(0,&empty,&p),"Map upload");memcpy(p,data,bytes);up->Unmap(0,nullptr);cmd->CopyBufferRegion(target,0,up.Get(),0,bytes);keep.push_back(up); }
static uint16_t narrow_half(float value) { uint32_t v;memcpy(&v,&value,4);uint16_t sign=(v>>16)&0x8000;uint32_t exp=(v>>23)&255,mant=v&0x7fffff;if(exp==255)return sign|0x7c00|(mant?0x200:0);int e=int(exp)-127+15;if(e>=31)return sign|0x7bff;if(e<=0){if(e<-10)return sign;return sign|((mant|0x800000)>>(14-e));}return sign|(e<<10)|(mant>>13); }
static float widen_half(uint16_t v) { int e=(v>>10)&31,m=v&1023;float x=e==0?std::ldexp(float(m),-24):(e==31?(m?std::numeric_limits<float>::quiet_NaN():std::numeric_limits<float>::infinity()):std::ldexp(float(m+1024),e-25));return v&0x8000?-x:x; }
static std::vector<unsigned char> pack_pixels(const float* values,size_t n,DXGI_FORMAT format) { size_t componentBytes=format==DXGI_FORMAT_R16G16B16A16_FLOAT?2:(format==DXGI_FORMAT_R8G8B8A8_UNORM?1:4);std::vector<unsigned char> bytes(n*componentBytes);for(size_t i=0;i<n;i++){if(componentBytes==2){uint16_t h=narrow_half(values[i]);memcpy(bytes.data()+i*2,&h,2);}else if(componentBytes==1){bytes[i]=(unsigned char)std::nearbyint(std::clamp(values[i],0.0f,1.0f)*255.0f);}else memcpy(bytes.data()+i*4,values+i,4);}return bytes; }
static ComPtr<ID3D12Resource> texture(ID3D12Device* dev,ID3D12GraphicsCommandList* cmd,DXGI_FORMAT format,int channels,const void* pixels,bool uav,std::vector<ComPtr<ID3D12Resource>>& keep) {
 D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;desc.Width=desc.Height=8;desc.DepthOrArraySize=desc.MipLevels=1;desc.Format=format;desc.SampleDesc.Count=1;desc.Flags=uav?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;
 auto out=resource(dev,desc,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COPY_DEST);D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};UINT rows;UINT64 rowBytes,total;dev->GetCopyableFootprints(&desc,0,1,0,&fp,&rows,&rowBytes,&total);
 auto packed=pack_pixels((const float*)pixels,8*8*channels,format);size_t sourceRow=packed.size()/8;auto up=resource(dev,buffer(total),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);void* p=nullptr;D3D12_RANGE empty{0,0};check(up->Map(0,&empty,&p),"Map texture upload");memset(p,0,(size_t)total);for(int y=0;y<8;y++)memcpy((char*)p+fp.Offset+y*fp.Footprint.RowPitch,packed.data()+y*sourceRow,sourceRow);up->Unmap(0,nullptr);
 D3D12_TEXTURE_COPY_LOCATION src{};src.pResource=up.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;src.PlacedFootprint=fp;D3D12_TEXTURE_COPY_LOCATION dst{};dst.pResource=out.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;cmd->CopyTextureRegion(&dst,0,0,0,&src,nullptr);
 transition(cmd,out.Get(),D3D12_RESOURCE_STATE_COPY_DEST,uav?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);keep.push_back(up);return out;
}
int main(int argc,char** argv) { try {
 if(argc!=5&&argc!=6)throw std::runtime_error("usage: shader_qa.exe fixture.bin shader.cso output-prefix adapter-substring [rgba16|rgba8|rgba32]");DXGI_FORMAT colorFormat=DXGI_FORMAT_R32G32B32A32_FLOAT;std::string formatName=argc==6?argv[5]:"rgba32";if(formatName=="rgba16")colorFormat=DXGI_FORMAT_R16G16B16A16_FLOAT;else if(formatName=="rgba8")colorFormat=DXGI_FORMAT_R8G8B8A8_UNORM;else if(formatName!="rgba32")throw std::runtime_error("unknown format");auto bytes=read(argv[1]);if(bytes.size()!=sizeof(Input))throw std::runtime_error("fixture size mismatch");Input input;memcpy(&input,bytes.data(),bytes.size());if(input.magic!=0x51555757||input.c.width!=8||input.c.height!=8)throw std::runtime_error("invalid fixture");auto shader=read(argv[2]);
 ComPtr<IDXGIFactory6> factory;check(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)),"CreateDXGIFactory2");ComPtr<IDXGIAdapter1> adapter;DXGI_ADAPTER_DESC1 ad{};bool found=false;
 for(UINT i=0;;i++){ComPtr<IDXGIAdapter1> candidate;HRESULT hr=factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&candidate));if(hr==DXGI_ERROR_NOT_FOUND)break;check(hr,"EnumAdapter");candidate->GetDesc1(&ad);std::wstring d(ad.Description);std::string description(d.begin(),d.end());if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&description.find(argv[4])!=std::string::npos){adapter=candidate;found=true;break;}}
 if(!found)throw std::runtime_error("Requested physical adapter not found; no WARP fallback");ComPtr<ID3D12Device> dev;check(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)),"D3D12CreateDevice");
 D3D12_FEATURE_DATA_FORMAT_SUPPORT fs{colorFormat};check(dev->CheckFeatureSupport(D3D12_FEATURE_FORMAT_SUPPORT,&fs,sizeof(fs)),"Check typed UAV support");if(!(fs.Support2&D3D12_FORMAT_SUPPORT2_UAV_TYPED_LOAD)||!(fs.Support2&D3D12_FORMAT_SUPPORT2_UAV_TYPED_STORE))throw std::runtime_error("Requested format typed UAV load/store unavailable");
 ComPtr<ID3D12CommandQueue> queue;D3D12_COMMAND_QUEUE_DESC qd{};qd.Type=D3D12_COMMAND_LIST_TYPE_DIRECT;check(dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)),"CreateCommandQueue");ComPtr<ID3D12CommandAllocator> allocator;check(dev->CreateCommandAllocator(qd.Type,IID_PPV_ARGS(&allocator)),"CreateCommandAllocator");ComPtr<ID3D12GraphicsCommandList> cmd;check(dev->CreateCommandList(0,qd.Type,allocator.Get(),nullptr,IID_PPV_ARGS(&cmd)),"CreateCommandList");
 D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0].RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_SRV;ranges[0].NumDescriptors=4;ranges[1].RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_UAV;ranges[1].NumDescriptors=1;
 D3D12_ROOT_PARAMETER roots[5]{};for(int i=0;i<2;i++){roots[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;roots[i].DescriptorTable.NumDescriptorRanges=1;roots[i].DescriptorTable.pDescriptorRanges=&ranges[i];}
 for(int i=2;i<4;i++){roots[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;roots[i].Descriptor.ShaderRegister=i-1;}roots[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;roots[4].Constants.Num32BitValues=20;
 D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=5;rd.pParameters=roots;ComPtr<ID3DBlob> signature,error;check(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&signature,&error),"Serialize root signature");ComPtr<ID3D12RootSignature> root;check(dev->CreateRootSignature(0,signature->GetBufferPointer(),signature->GetBufferSize(),IID_PPV_ARGS(&root)),"CreateRootSignature");
 D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.CS={shader.data(),shader.size()};ComPtr<ID3D12PipelineState> pso;check(dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)),"CreateComputePipelineState");
 std::vector<ComPtr<ID3D12Resource>> keep;std::array<ComPtr<ID3D12Resource>,5> textures{
 texture(dev.Get(),cmd.Get(),colorFormat,4,input.current.data(),false,keep),
 texture(dev.Get(),cmd.Get(),colorFormat,4,input.edited.data(),false,keep),
 texture(dev.Get(),cmd.Get(),DXGI_FORMAT_R32G32_FLOAT,2,input.motion.data(),false,keep),
 texture(dev.Get(),cmd.Get(),DXGI_FORMAT_R32_FLOAT,1,input.depth.data(),false,keep),
 texture(dev.Get(),cmd.Get(),colorFormat,4,input.edited.data(),true,keep)};
 auto previous=resource(dev.Get(),buffer(1280,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COPY_DEST);uploadbuffer(dev.Get(),cmd.Get(),previous.Get(),input.history.data(),1280,keep);transition(cmd.Get(),previous.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);auto next=resource(dev.Get(),buffer(1280,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
 D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=5;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ComPtr<ID3D12DescriptorHeap> descriptors;check(dev->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&descriptors)),"CreateDescriptorHeap");UINT step=dev->GetDescriptorHandleIncrementSize(hd.Type);auto cpu=descriptors->GetCPUDescriptorHandleForHeapStart();for(int i=0;i<4;i++){D3D12_SHADER_RESOURCE_VIEW_DESC s{};s.Format=textures[i]->GetDesc().Format;s.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;s.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;s.Texture2D.MipLevels=1;dev->CreateShaderResourceView(textures[i].Get(),&s,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC u{};u.Format=textures[4]->GetDesc().Format;u.ViewDimension=D3D12_UAV_DIMENSION_TEXTURE2D;dev->CreateUnorderedAccessView(textures[4].Get(),nullptr,&u,cpu);
 ID3D12DescriptorHeap* dh=descriptors.Get();cmd->SetDescriptorHeaps(1,&dh);cmd->SetComputeRootSignature(root.Get());cmd->SetPipelineState(pso.Get());auto gpu=descriptors->GetGPUDescriptorHandleForHeapStart();cmd->SetComputeRootDescriptorTable(0,gpu);gpu.ptr+=4*step;cmd->SetComputeRootDescriptorTable(1,gpu);cmd->SetComputeRootUnorderedAccessView(2,previous->GetGPUVirtualAddress());cmd->SetComputeRootUnorderedAccessView(3,next->GetGPUVirtualAddress());cmd->SetComputeRoot32BitConstants(4,20,&input.c,0);cmd->Dispatch(1,1,1);
 D3D12_RESOURCE_BARRIER ub[2]{};ub[0].Type=ub[1].Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;ub[0].UAV.pResource=textures[4].Get();ub[1].UAV.pResource=next.Get();cmd->ResourceBarrier(2,ub);transition(cmd.Get(),textures[4].Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);transition(cmd.Get(),next.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);
 D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};UINT rows;UINT64 rowbytes,total;auto td=textures[4]->GetDesc();dev->GetCopyableFootprints(&td,0,1,0,&fp,&rows,&rowbytes,&total);auto outread=resource(dev.Get(),buffer(total),D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);auto histread=resource(dev.Get(),buffer(1280),D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);D3D12_TEXTURE_COPY_LOCATION dst{};dst.pResource=outread.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=fp;D3D12_TEXTURE_COPY_LOCATION src{};src.pResource=textures[4].Get();src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;cmd->CopyTextureRegion(&dst,0,0,0,&src,nullptr);cmd->CopyBufferRegion(histread.Get(),0,next.Get(),0,1280);check(cmd->Close(),"Close command list");ID3D12CommandList* list=cmd.Get();queue->ExecuteCommandLists(1,&list);
 ComPtr<ID3D12Fence> fence;check(dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)),"CreateFence");HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!event)throw std::runtime_error("CreateEvent failed");check(queue->Signal(fence.Get(),1),"Signal");check(fence->SetEventOnCompletion(1,event),"SetEventOnCompletion");DWORD waited=WaitForSingleObject(event,5000);CloseHandle(event);if(waited!=WAIT_OBJECT_0) { std::cerr<<"GPU fence failed or timed out (5000ms); terminating process without releasing pending resources\n";ExitProcess(3); }
 std::array<float,256> output{};void* mapped=nullptr;D3D12_RANGE range{0,(SIZE_T)total};check(outread->Map(0,&range,&mapped),"Map output readback");for(int y=0;y<8;y++){auto row=(unsigned char*)mapped+fp.Offset+y*fp.Footprint.RowPitch;for(int x=0;x<32;x++){if(colorFormat==DXGI_FORMAT_R16G16B16A16_FLOAT){uint16_t h;memcpy(&h,row+x*2,2);output[y*32+x]=widen_half(h);}else if(colorFormat==DXGI_FORMAT_R8G8B8A8_UNORM)output[y*32+x]=float(row[x])/255.0f;else memcpy(output.data()+y*32+x,row+x*4,4);}}outread->Unmap(0,nullptr);range.End=1280;check(histread->Map(0,&range,&mapped),"Map history readback");write(std::string(argv[3])+".history.bin",mapped,1280);histread->Unmap(0,nullptr);write(std::string(argv[3])+".output.bin",output.data(),1024);
 std::wstring wide(ad.Description);std::string desc(wide.begin(),wide.end());std::cout<<"{\"adapter\":\""<<desc<<"\",\"vendor_id\":"<<ad.VendorId<<",\"device_id\":"<<ad.DeviceId<<",\"dedicated_video_memory\":"<<ad.DedicatedVideoMemory<<",\"mode\":"<<input.mode<<",\"pixels\":64,\"record_bytes\":20,\"fence_completed\":true,\"fence_timeout_ms\":5000,\"format\":\""<<formatName<<"\",\"typed_uav_load_store\":true}"<<std::endl;return 0;
 } catch(const std::exception& e) { std::cerr<<e.what()<<std::endl;return 1; } }
