// Isolated shader cost fixture. No NGX/NR/game code runs in this process.
#define main numeric_qa_main
#include "shader_qa.cpp"
#undef main
#include <algorithm>
static ComPtr<ID3D12Resource> bench_texture(ID3D12Device* dev,ID3D12GraphicsCommandList* cmd,DXGI_FORMAT format,int channels,const std::array<float,4>& value,bool uav,std::vector<ComPtr<ID3D12Resource>>& keep) {
 D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;desc.Width=2560;desc.Height=1440;desc.DepthOrArraySize=desc.MipLevels=1;desc.Format=format;desc.SampleDesc.Count=1;desc.Flags=uav?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;
 auto out=resource(dev,desc,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COPY_DEST);D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};UINT rows;UINT64 rowBytes,total;dev->GetCopyableFootprints(&desc,0,1,0,&fp,&rows,&rowBytes,&total);
 std::vector<float> row(2560*channels);for(int x=0;x<2560;x++)for(int c=0;c<channels;c++)row[x*channels+c]=value[c];auto packed=pack_pixels(row.data(),row.size(),format);auto up=resource(dev,buffer(total),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);void* p=nullptr;D3D12_RANGE empty{0,0};check(up->Map(0,&empty,&p),"Map benchmark upload");memset(p,0,(size_t)total);for(int y=0;y<1440;y++)memcpy((char*)p+fp.Offset+y*fp.Footprint.RowPitch,packed.data(),packed.size());up->Unmap(0,nullptr);
 D3D12_TEXTURE_COPY_LOCATION src{};src.pResource=up.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;src.PlacedFootprint=fp;D3D12_TEXTURE_COPY_LOCATION dst{};dst.pResource=out.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;cmd->CopyTextureRegion(&dst,0,0,0,&src,nullptr);transition(cmd,out.Get(),D3D12_RESOURCE_STATE_COPY_DEST,uav?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);keep.push_back(up);return out;
}
static void uav_order(ID3D12GraphicsCommandList* cmd) { D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;b.UAV.pResource=nullptr;cmd->ResourceBarrier(1,&b); }
int main(int argc,char** argv) { try {
 if(argc!=3&&argc!=4)throw std::runtime_error("usage: shader_timing refresh.cso reproject.cso [rgba16|rgba32]");std::string fmt=argc==4?argv[3]:"rgba16";DXGI_FORMAT colorFormat=fmt=="rgba16"?DXGI_FORMAT_R16G16B16A16_FLOAT:DXGI_FORMAT_R32G32B32A32_FLOAT;if(fmt!="rgba16"&&fmt!="rgba32")throw std::runtime_error("Unsupported benchmark format");auto refresh=read(argv[1]);auto reproject=read(argv[2]);
 ComPtr<IDXGIFactory6> factory;check(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)),"CreateDXGIFactory2");ComPtr<IDXGIAdapter1> adapter;DXGI_ADAPTER_DESC1 ad{};bool found=false;for(UINT i=0;;i++){ComPtr<IDXGIAdapter1> candidate;HRESULT hr=factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&candidate));if(hr==DXGI_ERROR_NOT_FOUND)break;check(hr,"EnumAdapter");candidate->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&std::wstring(ad.Description).find(L"RTX 5070")!=std::wstring::npos){adapter=candidate;found=true;break;}}if(!found)throw std::runtime_error("RTX 5070 absent; WARP is disallowed");ComPtr<ID3D12Device> dev;check(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)),"D3D12CreateDevice");D3D12_FEATURE_DATA_FORMAT_SUPPORT fs{colorFormat};check(dev->CheckFeatureSupport(D3D12_FEATURE_FORMAT_SUPPORT,&fs,sizeof(fs)),"Typed UAV support");if(!(fs.Support2&D3D12_FORMAT_SUPPORT2_UAV_TYPED_LOAD)||!(fs.Support2&D3D12_FORMAT_SUPPORT2_UAV_TYPED_STORE))throw std::runtime_error("Selected color format typed UAV unsupported");
 ComPtr<ID3D12CommandQueue> queue;D3D12_COMMAND_QUEUE_DESC qd{};qd.Type=D3D12_COMMAND_LIST_TYPE_DIRECT;check(dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)),"Create queue");UINT64 frequency=0;check(queue->GetTimestampFrequency(&frequency),"Timestamp frequency");ComPtr<ID3D12CommandAllocator> allocator;check(dev->CreateCommandAllocator(qd.Type,IID_PPV_ARGS(&allocator)),"Create allocator");ComPtr<ID3D12GraphicsCommandList> cmd;check(dev->CreateCommandList(0,qd.Type,allocator.Get(),nullptr,IID_PPV_ARGS(&cmd)),"Create command list");
 D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0].RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_SRV;ranges[0].NumDescriptors=4;ranges[1].RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_UAV;ranges[1].NumDescriptors=1;D3D12_ROOT_PARAMETER roots[5]{};for(int i=0;i<2;i++){roots[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;roots[i].DescriptorTable.NumDescriptorRanges=1;roots[i].DescriptorTable.pDescriptorRanges=&ranges[i];}for(int i=2;i<4;i++){roots[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;roots[i].Descriptor.ShaderRegister=i-1;}roots[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;roots[4].Constants.Num32BitValues=20;D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=5;rd.pParameters=roots;ComPtr<ID3DBlob> sig,err;check(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&err),"Serialize root");ComPtr<ID3D12RootSignature> root;check(dev->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root)),"Create root");std::array<ComPtr<ID3D12PipelineState>,2> psos;D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.CS={refresh.data(),refresh.size()};check(dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&psos[0])),"Refresh PSO");pd.CS={reproject.data(),reproject.size()};check(dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&psos[1])),"Reproject PSO");
 std::vector<ComPtr<ID3D12Resource>> keep;std::array<ComPtr<ID3D12Resource>,5> textures{
 bench_texture(dev.Get(),cmd.Get(),colorFormat,4,{.25f,.3125f,.375f,1},false,keep),
 bench_texture(dev.Get(),cmd.Get(),colorFormat,4,{.28125f,.296875f,.4375f,1},false,keep),
 bench_texture(dev.Get(),cmd.Get(),DXGI_FORMAT_R32G32_FLOAT,2,{0,0,0,0},false,keep),
 bench_texture(dev.Get(),cmd.Get(),DXGI_FORMAT_R32_FLOAT,1,{.5f,0,0,0},false,keep),
 bench_texture(dev.Get(),cmd.Get(),colorFormat,4,{.28125f,.296875f,.4375f,1},true,keep)};
 const UINT64 historyBytes=2560ull*1440*20;auto a=resource(dev.Get(),buffer(historyBytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);auto b=resource(dev.Get(),buffer(historyBytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
 D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=5;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ComPtr<ID3D12DescriptorHeap> descriptors;check(dev->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&descriptors)),"Descriptor heap");UINT step=dev->GetDescriptorHandleIncrementSize(hd.Type);auto cpu=descriptors->GetCPUDescriptorHandleForHeapStart();for(int i=0;i<4;i++){D3D12_SHADER_RESOURCE_VIEW_DESC s{};s.Format=textures[i]->GetDesc().Format;s.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;s.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;s.Texture2D.MipLevels=1;dev->CreateShaderResourceView(textures[i].Get(),&s,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC u{};u.Format=textures[4]->GetDesc().Format;u.ViewDimension=D3D12_UAV_DIMENSION_TEXTURE2D;dev->CreateUnorderedAccessView(textures[4].Get(),nullptr,&u,cpu);
 D3D12_QUERY_HEAP_DESC qh{};qh.Type=D3D12_QUERY_HEAP_TYPE_TIMESTAMP;qh.Count=48;ComPtr<ID3D12QueryHeap> queries;check(dev->CreateQueryHeap(&qh,IID_PPV_ARGS(&queries)),"Query heap");auto queryRead=resource(dev.Get(),buffer(48*8),D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);ID3D12DescriptorHeap* dh=descriptors.Get();cmd->SetDescriptorHeaps(1,&dh);cmd->SetComputeRootSignature(root.Get());auto gpu=descriptors->GetGPUDescriptorHandleForHeapStart();cmd->SetComputeRootDescriptorTable(0,gpu);gpu.ptr+=4*step;cmd->SetComputeRootDescriptorTable(1,gpu);Constants c{2560,1440,2560,1440,2560,1440,0,0,0,0,2,32,1,1,.0001f,.01f,.20f,.15f,.02f,0};cmd->SetComputeRoot32BitConstants(4,20,&c,0);
 // Alternating fresh/reuse base-frame fixture. A receives the fresh capture,
 // then is read by reuse, which writes B. The next refresh rewrites A only
 // after a global UAV barrier orders the preceding reads and writes.
 for(int round=0;round<12;round++)for(int kernel=0;kernel<2;kernel++){
  cmd->SetPipelineState(psos[kernel].Get());cmd->SetComputeRootUnorderedAccessView(2,kernel==0?b->GetGPUVirtualAddress():a->GetGPUVirtualAddress());cmd->SetComputeRootUnorderedAccessView(3,kernel==0?a->GetGPUVirtualAddress():b->GetGPUVirtualAddress());UINT query=round*4+kernel*2;cmd->EndQuery(queries.Get(),D3D12_QUERY_TYPE_TIMESTAMP,query);cmd->Dispatch(320,180,1);uav_order(cmd.Get());cmd->EndQuery(queries.Get(),D3D12_QUERY_TYPE_TIMESTAMP,query+1);
 }
 cmd->ResolveQueryData(queries.Get(),D3D12_QUERY_TYPE_TIMESTAMP,0,48,queryRead.Get(),0);check(cmd->Close(),"Close");ID3D12CommandList* list=cmd.Get();queue->ExecuteCommandLists(1,&list);ComPtr<ID3D12Fence> fence;check(dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)),"Fence");HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!event)throw std::runtime_error("Fence event");check(queue->Signal(fence.Get(),1),"Signal fence");check(fence->SetEventOnCompletion(1,event),"Set fence event");auto wait=WaitForSingleObject(event,5000);CloseHandle(event);if(wait!=WAIT_OBJECT_0){std::cerr<<"5000ms fence timeout; terminating without pending-resource release\n";ExitProcess(3);}D3D12_RANGE range{0,48*8};void* mapped=nullptr;check(queryRead->Map(0,&range,&mapped),"Timestamp readback");std::array<UINT64,48> ts{};memcpy(ts.data(),mapped,48*8);queryRead->Unmap(0,nullptr);
 std::array<std::vector<double>,2> samples;double totalMs=0;for(int round=0;round<12;round++)for(int kernel=0;kernel<2;kernel++){int i=round*4+kernel*2;if(ts[i+1]<ts[i])throw std::runtime_error("Timestamp ordering failure");double ms=double(ts[i+1]-ts[i])*1000/double(frequency);totalMs+=ms;if(round>=2)samples[kernel].push_back(ms);}
 std::cout<<std::setprecision(9)<<"{\"adapter\":\"NVIDIA GeForce RTX 5070\",\"fixture\":\"product full-edited cache; isolated kernels, no NGX/NR/game\",\"width\":2560,\"height\":1440,\"warmups_per_kernel\":2,\"samples_per_kernel\":10,\"timestamp_frequency_hz\":"<<frequency<<",\"measured_gpu_total_ms_including_warmup\":"<<totalMs<<",\"fence_timeout_ms\":5000,\"fence_completed\":true,\"queue\":\"one own-process direct queue\",\"texture_format\":\"current/edited/output "<<(fmt=="rgba16"?"RGBA16_FLOAT":"RGBA32_FLOAT")<<", motion RG32_FLOAT, depth R32_FLOAT\",\"init\":\"full texture upload before timestamps; uniform linear baseline and synthetic full edited RGB, alpha1, depth0.5; all-zero full-resolution motion\",\"history\":\"2x20B/pixel full-edited/reference half records, default-heap UAV buffers, refreshed A then reproject A-to-B; global UAV ordering each dispatch\",\"timed\":\"Dispatch plus following global UAV barrier; excludes init/upload, allocation, pipeline/root binding, query resolution, fence wait\",\"kernels\":[";
 for(int kernel=0;kernel<2;kernel++){auto sorted=samples[kernel];std::sort(sorted.begin(),sorted.end());double median=(sorted[4]+sorted[5])/2;double p95=sorted[8]+.55*(sorted[9]-sorted[8]);if(kernel)std::cout<<",";std::cout<<"{\"name\":\""<<(kernel==0?"refresh":"reproject")<<"\",\"median_ms\":"<<median<<",\"p95_ms\":"<<p95<<",\"samples_ms\":[";for(int i=0;i<10;i++){if(i)std::cout<<",";std::cout<<samples[kernel][i];}std::cout<<"]}";}
 std::cout<<"]}"<<std::endl;return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<std::endl;return 1;} }
